import type { Metadata } from "next";
import "./globals.css";
import CursorAura from "@/components/CursorAura"; // Make sure this path is correct
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Askus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* The 'overflow-x-hidden' class is added here.
        This is the key change that prevents horizontal scrolling across your entire site
        by hiding any content that overflows the viewport's width.
      */}
      <body className="overflow-x-hidden">
        {/* This component provides the logic and the div for the effect */}
        <CursorAura /> 
        
        {/* The rest of your app's pages will be rendered here */}
        {children}
        <Analytics />
      </body>
    </html>
  );
}
