// app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import CursorAura from "@/components/CursorAura"; // Make sure this path is correct

export const metadata: Metadata = {
  title: "Askus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* This component provides the logic and the div for the effect */}
        <CursorAura /> 
        
        {/* The rest of your app's pages will be rendered here */}
        {children}
      </body>
    </html>
  );
}